//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yhb_war3_custom_keys.res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("yhb_war3_custom_keys.res.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //////////////////////////////////////////////////////
        /////This file includes all racial units, heroes, 
        /////upgrades, buildings and abilities.  Please consult 
        /////CustomKeyInfo.txt for information on how to go about
        /////using this file for customized hotkey support.
        /////////////////////////////////////////////////////////
        ///
        ///
        ////////////////////////////////
        /////Shared Commands (attack, etc.)
        ////////////////////////////////
        ///
        /////move
        ///[CmdMove]
        ///Tip=|cffffcc00M|rove
        ///Hotkey=M
        ///
        /////attack
        ///[CmdAttack]
        ///Tip=|cffffcc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomKeysSample {
            get {
                return ResourceManager.GetString("CustomKeysSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //////////////////////////////////////////////////////
        /////这个文件包含所有的单位、英雄、
        /////升级、建筑物和技能。请
        /////参考CustomKeyInfo.txt来获取关于如何使用
        /////这个文件的信息。
        /////////////////////////////////////////////////////////
        ///
        ///
        ////////////////////////////////
        /////共享的命令（攻击等）
        ////////////////////////////////
        ///
        /////移动
        ///[CmdMove]
        ///Tip=(|cffffcc00M|r)移动
        ///Hotkey=M
        ///
        /////攻击
        ///[CmdAttack]
        ///Tip=(|cffffcc00A|r)攻击
        ///Hotkey=A
        ///
        /////攻击地面
        ///[CmdAttackGround]
        ///Tip= (|cffffcc00G|r)攻击地面
        ///Hotkey=G
        ///
        /////建造建筑物（一般的）
        ///[CmdBuild]
        ///Tip=(|cffffcc00B|r)建造建筑物
        ///Hotkey=B
        ///
        /////建造建 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomKeysSample_cn {
            get {
                return ResourceManager.GetString("CustomKeysSample_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warcraft III Custom Keys Editor.
        /// </summary>
        internal static string S_APP_NAME {
            get {
                return ResourceManager.GetString("S_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string S_CANCEL {
            get {
                return ResourceManager.GetString("S_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Key Defines.
        /// </summary>
        internal static string S_DEFAULT_KEY_DEFINES {
            get {
                return ResourceManager.GetString("S_DEFAULT_KEY_DEFINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string S_ERROR {
            get {
                return ResourceManager.GetString("S_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expect a filename after the {0} option..
        /// </summary>
        internal static string S_EXPECT_FILENAME_AFTER_FILE_OPTION {
            get {
                return ResourceManager.GetString("S_EXPECT_FILENAME_AFTER_FILE_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Hotkey&apos; define not found..
        /// </summary>
        internal static string S_HOTKEY_DEFINE_NOT_FOUND {
            get {
                return ResourceManager.GetString("S_HOTKEY_DEFINE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command line.
        /// </summary>
        internal static string S_INVALID_CMDLINE {
            get {
                return ResourceManager.GetString("S_INVALID_CMDLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid line..
        /// </summary>
        internal static string S_INVALID_LINE {
            get {
                return ResourceManager.GetString("S_INVALID_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string S_LINE {
            get {
                return ResourceManager.GetString("S_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string S_OK {
            get {
                return ResourceManager.GetString("S_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string S_PAGE_BUILDING {
            get {
                return ResourceManager.GetString("S_PAGE_BUILDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string S_PAGE_COMMON {
            get {
                return ResourceManager.GetString("S_PAGE_COMMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroes.
        /// </summary>
        internal static string S_PAGE_HEROES {
            get {
                return ResourceManager.GetString("S_PAGE_HEROES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string S_PAGE_HUMAN {
            get {
                return ResourceManager.GetString("S_PAGE_HUMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        internal static string S_PAGE_NEUTRAL {
            get {
                return ResourceManager.GetString("S_PAGE_NEUTRAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Elves.
        /// </summary>
        internal static string S_PAGE_NIGHT_ELVES {
            get {
                return ResourceManager.GetString("S_PAGE_NIGHT_ELVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.
        /// </summary>
        internal static string S_PAGE_ORC {
            get {
                return ResourceManager.GetString("S_PAGE_ORC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undead.
        /// </summary>
        internal static string S_PAGE_UNDEAD {
            get {
                return ResourceManager.GetString("S_PAGE_UNDEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string S_PAGE_UNITS {
            get {
                return ResourceManager.GetString("S_PAGE_UNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section define expected..
        /// </summary>
        internal static string S_SECTION_DEFINE_EXPECTED {
            get {
                return ResourceManager.GetString("S_SECTION_DEFINE_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown option &apos;{0}&apos;..
        /// </summary>
        internal static string S_UNKNOWN_OPTION {
            get {
                return ResourceManager.GetString("S_UNKNOWN_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled - {0}.
        /// </summary>
        internal static string S_UNTITLED {
            get {
                return ResourceManager.GetString("S_UNTITLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string S_WARNING {
            get {
                return ResourceManager.GetString("S_WARNING", resourceCulture);
            }
        }
    }
}
