using System.Diagnostics;
using System.Security.Cryptography;

namespace yhb_war3_custom_keys.model {
    public static class KeyDefinesGroup {

        public struct Entry {
            public readonly string SectionName;
            public readonly string Description;
            public Entry(string secitonName, string caption) {
                this.SectionName = secitonName;
                this.Description = caption;
            }
        }

        public static readonly Entry[] COMMON_ENTRIES = new Entry[] {
            new("CmdMove", "移动"),
            new("CmdAttack", "攻击"),
            new("CmdAttackGround", "攻击地面"),
            new("CmdBuild", "建造建筑物（一般的）"),
            new("CmdBuildHuman", "建造建筑物（人类）"),
            new("CmdBuildOrc", "建造建筑物（兽族）"),
            new("CmdBuildNightElf", "建造建筑物（暗夜精灵）"),
            new("CmdBuildUndead", "召唤建筑物（亡灵）"),
            new("CmdCancel", "取消"),
            new("CmdCancelBuild", "取消建造"),
            new("CmdCancelTrain", "取消训练"),
            new("CmdCancelRevive", "取消复活"),
            new("CmdHoldPos", "保持原位"),
            new("CmdPatrol", "巡逻"),
            new("CmdRally", "设集结点"),
            new("CmdSelectSkill", "英雄技能"),
            new("CmdStop", "停止"),
            new("Ahar", "采集"),
            new("Ahrl", "采集木材"),
            new("Arep", "农民修理技能"),
            new("Anei", "中立单位的互动（选择用户命令）"),
            new("Aloa", "装载"),
            new("Adro", "卸载全部"),
            new("Sdro", "卸载（海上运输工具）"),
        };

        public static readonly List<Entry[]>[] RACE_ENTRIES = new [] {
            new List<Entry[]>(3),
            new List<Entry[]>(3),
            new List<Entry[]>(3),
            new List<Entry[]>(3),
        };

        static KeyDefinesGroup() {

            #region Human
            var race = RACE_ENTRIES[0];
            race.Add(new Entry[] {
                new("Hblm", "血法师"),
                new("AHdr", "魔法吸吮"),
                new("AHfs", "烈焰风暴"),
                new("AHbn", "驱散"),
                new("AHpx", "凤凰"),
                new("Hamg", "大魔法师"),
                new("AHbz", "暴风雪"),
                new("AHwe", "召唤水元素"),
                new("AHab", "辉煌光环 "),
                new("AHmt", "群体传送"),
                new("Hmkg", "山丘之王"),
                new("AHtb", "风暴之锤"),
                new("AHtc", "雷霆一击"),
                new("AHbh", "重击 "),
                new("AHav", "天神下凡"),
                new("Hpal", "圣骑士"),
                new("AHhb", "神圣之光"),
                new("AHds", "神圣护甲"),
                new("AHad", "专注光环"),
                new("AHre", "复活"),
            });
            race.Add(new Entry[] {
                new("hdhw", "龙鹰骑士 "),
                new("Amls", "空中锁镣"),
                new("Aclf", "乌云"),
                new("hfoo", "步兵"),
                new("Adef", "防御"),
                new("hgyr", "飞行机器 "),
                new("hkni", "骑士"),
                new("hmpr", "牧师"),
                new("Ainf", "心灵之火"),
                new("Ahea", "医疗"),
                new("Adis", "驱逐魔法"),
                new("hmtm", "迫击炮小队"),
                new("Afla", "照明弹"),
                new("hpea", "农民"),
                new("Amil", "战斗号召（一个或者多个农民）"),
                new("Amic", "战斗号召（让城镇大厅附近的农民都集合到一起）"),
                new("hrif", "矮人火枪手"),
                new("hsor", "女妖"),
                new("Aslo", "减速"),
                new("Aply", "变形术"),
                new("Aivs", "隐形术"),
                new("hspt", "魔法破坏者"),
                new("Asps", "魔法盗取"),
                new("Acmg", "控制魔法"),
                new("hmtt", "蒸汽机车（不带弹幕攻击）"),
                new("hrtt", "蒸汽机车（带弹幕攻击）"),
                new("hgry", "狮鹫骑士"),
            });
            race.Add(new Entry[] {
                new("Rhss", "魔法控制"),
                new("Rhme", "剑术升级"),
                new("Rhra", "火药升级"),
                new("Rhar", "护甲升级"),
                new("Rhla", "皮甲升级"),
                new("Rhac", "石工技术升级"),
                new("Rhgb", "飞行机器炸弹"),
                new("Rhlh", "改进伐木效率"),
                new("Rhde", "防御升级"),
                new("Rhan", "动物作战训练"),
                new("Rhpt", "牧师训练升级"),
                new("Rhst", "女巫训练升级"),
                new("Rhri", "长管火枪升级"),
                new("Rhse", "魔法岗哨升级"),
                new("Rhfl", "照明弹"),
                new("Rhhb", "风暴战锤"),
                new("Rhrt", "弹幕攻击"),
                new("Rhpm", "背包技能"),
                new("Rhfc", "高射炮火"),
                new("Rhfs", "碎片攻击"),
                new("Rhcd", "乌云"),
                new("halt", "国王祭坛"),
                new("harm", "车间"),
                new("hars", "神秘圣地"),
                new("hbar", "兵营"),
                new("hbla", "铁匠铺"),
                new("hcas", "城堡"),
                new("hhou", "农场"),
                new("hgra", "狮鹫笼"),
                new("hctw", "炮塔"),
                new("hgtw", "防御塔"),
                new("hwtw", "哨塔"),
                new("hatw", "神秘之塔"),
                new("AHta", "显示"),
                new("hvlt", "神秘藏宝室"),
                new("hlum", "伐木场"),
                new("hkee", "主城"),
                new("htow", "城镇大厅"),
            });
            #endregion

            #region Orc
            race = RACE_ENTRIES[1];
            race.Add(new Entry[] {
                new("Obla", "剑圣"),
                new("AOwk", "疾步风"),
                new("AOcr", "致命一击 "),
                new("AOmi", "镜像"),
                new("AOww", "剑刃风暴"),
                new("Ofar", "先知"),
                new("AOcl", "闪电链"),
                new("AOfs", "透视"),
                new("AOsf", "野兽幽魂"),
                new("AOeq", "地震"),
                new("Oshd", "暗影猎手"),
                new("AOhw", "医疗波"),
                new("AOsw", "毒蛇守卫"),
                new("AOhx", "妖术 "),
                new("AOvd", "巫毒"),
                new("Otch", "牛头人酋长"),
                new("AOsh", "震荡波"),
                new("AOae", "耐久光环"),
                new("AOws", "战争践踏"),
                new("AOre", "重生"),
            });
            race.Add(new Entry[] {
                new("ocat", "粉碎者"),
                new("odoc", "巨魔巫医"),
                new("Aeye", "岗哨守卫"),
                new("Asta", "静止陷阱"),
                new("Ahwd", "医疗守卫"),
                new("ogru", "兽族步兵"),
                new("ohun", "巨魔猎头者"),
                new("otbk", "巨魔狂暴战士"),
                new("Absk", "狂热愤怒"),
                new("okod", "科多兽"),
                new("Adev", "吞噬魔法"),
                new("opeo", "苦工"),
                new("orai", "掠夺者"),
                new("Aens", "诱捕"),
                new("oshm", "萨满祭司"),
                new("Aprg", "净化"),
                new("Ablo", "嗜血术"),
                new("Alsh", "闪电护盾"),
                new("otau", "牛头人"),
                new("otbr", "巨魔蝙蝠骑士"),
                new("Auco", "不稳定化合物"),
                new("owyv", "风骑士"),
                new("ospm", "灵魂行者"),
                new("Aast", "先祖幽灵"),
                new("Adcn", "消魔"),
                new("Acpf", "灵肉形态"),
                new("Aetf", "虚无形态"),
                new("Aspl", "灵魂锁链"),
            });
            race.Add(new Entry[] {
                new("Rome", "近战武器升级"),
                new("Rora", "远程武器升级"),
                new("Roar", "护甲升级"),
                new("Rwdm", "战鼓"),
                new("Ropg", "掠夺"),
                new("Robs", "狂暴力量"),
                new("Rows", "粉碎"),
                new("Roen", "诱捕"),
                new("Rovs", "浸毒武器"),
                new("Rowd", "巫医训练升级"),
                new("Rost", "萨满祭司训练升级"),
                new("Rosp", "尖刺障碍升级"),
                new("Rotr", "巨魔再生升级"),
                new("Rolf", "液体炸弹升级"),
                new("Ropm", "背包技能"),
                new("Rowt", "灵魂行者训练升级"),
                new("Robk", "狂暴愤怒升级"),
                new("Rorb", "加强型防御"),
                new("Robf", "燃烧之油"),
                new("oalt", "风暴祭坛"),
                new("obar", "兵营"),
                new("obea", "兽栏"),
                new("ofor", "战争磨坊"),
                new("ofrt", "堡垒"),
                new("ogre", "大厅"),
                new("osld", "灵魂归宿"),
                new("ostr", "要塞"),
                new("otrb", "兽族地洞"),
                new("Abtl", "战备状态"),
                new("Astd", "卸载苦工"),
                new("orbr", "加强型地洞"),
                new("otto", "牛头人图腾"),
                new("ovln", "巫毒商店"),
                new("owtw", "了望塔"),
            });
            #endregion

            #region Undead
            race = RACE_ENTRIES[2];
            race.Add(new Entry[] {
                new("Ucrl", "地穴领主"),
                new("AUim", "穿刺"),
                new("AUts", "尖刺外壳"),
                new("AUcb", "腐尸甲虫"),
                new("Abu2", "钻地（等级2）"),
                new("Abu3", "钻地（等级3）"),
                new("AUls", "蝗虫群"),
                new("Udea", "死亡骑士"),
                new("AUdc", "死亡缠绕"),
                new("AUau", "邪恶光环"),
                new("AUdp", "死亡契约"),
                new("AUan", "操纵死尸"),
                new("Udre", "恐惧魔王"),
                new("AUcs", "腐臭蜂群"),
                new("AUsl", "睡眠"),
                new("AUav", "吸血光环"),
                new("AUin", "地狱火"),
                new("Ulic", "巫妖"),
                new("AUfn", "霜冻新星"),
                new("AUfu", "霜冻护甲"),
                new("AUdr", "黑暗仪式"),
                new("AUdd", "死亡凋零"),
            });
            race.Add(new Entry[] {
                new("uaco", "侍僧"),
                new("Auns", "反召唤建筑物"),
                new("Aaha", " 采集"),
                new("Arst", "恢复"),
                new("uabo", "憎恶"),
                new("Acn2", "吞食尸体"),
                new("uban", "女妖"),
                new("Acrs", "诅咒"),
                new("Aams", "反魔法外壳"),
                new("Aam2", "反魔法外壳"),
                new("Apos", "占据"),
                new("Aps2", "占据"),
                new("ucry", "穴居恶魔"),
                new("Aweb", "蛛网"),
                new("Abur", "钻地"),
                new("ufro", "冰霜巨龙"),
                new("ugar", "石像鬼"),
                new("Astn", "石像形态"),
                new("ugho", "食尸鬼"),
                new("Acan", " 吞食尸体"),
                new("unec", "亡灵巫师"),
                new("Arai", "复活死尸"),
                new("Auhf", "邪恶狂热"),
                new("Acri", "残废"),
                new("umtw", "绞肉车"),
                new("Amel", "得到尸体"),
                new("Amed", "卸载尸体"),
                new("uobs", "十胜石雕像"),
                new("Arpm", "灵魂触摸"),
                new("Arpl", "枯萎精髓"),
                new("ubsp", "变形为破坏者"),
                new("Afak", "毁灭之球"),
                new("Advm", "吞噬魔法"),
                new("Aabs", "吸收魔法"),
            });
            race.Add(new Entry[] {
                new("Rusp", "研究破坏者形态"),
                new("Rume", "邪恶力量升级"),
                new("Rura", "生物攻击升级"),
                new("Ruar", "邪恶装甲升级"),
                new("Rucr", "生物甲壳升级"),
                new("Ruac", "吞食尸体"),
                new("Rugf", "食尸鬼狂热"),
                new("Ruwb", "蛛网"),
                new("Rusf", "石像形态"),
                new("Rune", "亡灵巫师训练升级"),
                new("Ruba", "女妖训练升级"),
                new("Rufb", "冰冻喷吐"),
                new("Rusl", "骨质增强术"),
                new("Rupc", "疾病云雾"),
                new("Rusm", "骷髅法术"),
                new("Rubu", "钻地"),
                new("Ruex", "挖掘尸体"),
                new("Rupm", "背包技能"),
                new("ubon", "埋骨地"),
                new("usap", "牺牲深渊"),
                new("Alam", "牺牲"),
                new("uslh", "屠宰场"),
                new("ugrv", "坟场"),
                new("uaod", "黑暗祭坛"),
                new("unpl", "大墓地"),
                new("unp1", "亡者大厅"),
                new("unp2", "黑色城堡"),
                new("usep", "地穴"),
                new("utod", "诅咒神庙"),
                new("utom", "古墓废墟"),
                new("ugol", "闹鬼金矿"),
                new("uzig", "通灵塔"),
                new("uzg1", "幽魂之塔"),
                new("uzg2", "蛛网怪塔"),
            });
            #endregion
        }
    }
}
